services:

  exp_engine:
    build: ./exp_engine
    container_name: exp-eng-service
    ports:
      - '5556:5556'
    networks:
      - my_net


networks:
  my_net:
    name: extremexp_network
    external: true
